version: 2
jobs:
  build:
    working_directory: ~/ionic/
    docker:
      - image: node:8.9
    branches:
      # ignore:
      #   - core
    steps:
      - checkout
      - restore_cache:
         key: node_modules_global_5.7
      - run:
         name: Install npm > v5.7
         command: npm i -g npm
      - save_cache:
         key: node_modules_global_5.7
         paths:
         - ~/ionic/node_modules/
      - restore_cache:
         key: node_modules_{{ checksum "package.json" }}
      - run:
         name: Install monorepo node modules
         command: npm ci
      - save_cache:
         key: node_modules_{{ checksum "package.json" }}
         paths:
         - ~/ionic/node_modules/
      - restore_cache:
         key: node_modules_{{ checksum "packages/core/package.json" }}
      - run:
         name: Install core node modules
         command: npm --prefix packages/core/ ci
      - save_cache:
         key: node_modules_{{ checksum "packages/core/package.json" }}
         paths:
         - ~/ionic/packages/core/node_modules/
      - run:
          name: Validate Core
          command: npm --prefix packages/core/ run validate